server:
  port: 8072

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: "http://localhost:8070/eureka/"
